baseurl = "https://sagedayswesterncanada.github.io"
languageCode = "en-us"
theme = "terminal"

relativeURLs = true

# Required for Chroma and the custom syntax highlighting.
[markup.highlight]
  noClasses = false

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 999

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = true
  enableGitInfo = true

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  # Set date/time format for posts
  # This will impact the date/time displayed on
  # index.html, the posts list page, and on posts themselves
  # This value can also be configured per-post on front matter
  # If you have any issues with the timezone rendering differently
  # than you expected, please ensure your timezone is correctly set
  # on your server.
  # This value can be customized according to Hugo documentation:
  # https://gohugo.io/functions/time/format/
  # Default value (no changes needed):
  # dateFormat = "2006-01-02"
  # Example format, with date, time, and timezone abbreviation:
  # dateFormat = "2006-01-02 3:04:06 PM MST"


[languages]
  [languages.en]
    languageName = "English"
    title = "Sage Days Western Canada 2026"

#     [languages.en.params]
#       subtitle = "A simple, retro theme for Hugo"
#       owner = ""
#       keywords = ""
#       copyright = ""
#       menuMore = "Show more"
#       readMore = "Read more"
#       readOtherPosts = "Read other posts"
#       newerPosts = "Newer posts"
#       olderPosts = "Older posts"
#       missingContentMessage = "Page not found..."
#       missingBackButtonLabel = "Back to home page"
#       minuteReadingTime = "min read"
#       words = "words"

      [languages.en.params.logo]
        logoText = "Sage Days Western Canada 2026: Rocky Mountains"
        logoHomeLink = "/"

        # Those added `index.html` are not pretty, but it's a quick and dirty
        # fix on the problems I had with exporting the public/ website for demo
        # purposes.

        [[languages.en.menu.main]]
          identifier = "home"
          name = "Home"
          url = "/"
          weight = 1

        [[languages.en.menu.main]]
          identifier = "activities"
          name = "Activities"
          url = "/activities/"

        [[languages.en.menu.main]]
          identifier = "registration"
          name = "Registration"
          url = "/registration"

        [[languages.en.menu.main]]
          identifier = "travel-visas"
          name = "Travel and visas"
          url = "/travel-visas"

        [[languages.en.menu.main]]
          identifier = "venue"
          name = "Venue"
          url = "/venue"


# For GitHub Pages deployment:
# https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
  [caches.images]
    dir = ':cacheDir/images'
